export declare const assertNotNull: (value: any, msg?: string) => void;
export declare const getAddress: (value: any) => string;
export declare const getTopics: (value: any) => (string | string[])[];
export declare const assertNotType: (value: any, type: string, msg?: string) => void;
export declare const numberToHex: (value: any) => string;
export declare const isHex: (value: any) => boolean;
export declare const getHex: <T extends unknown>(value: any) => T;
export declare const hexToNumber: (value: string) => number;
export declare const toLowerCase: (value: string) => string;
export declare const toHexString: (value: string) => string;
export declare const isNumber: (data: any) => boolean;
//# sourceMappingURL=utils.d.ts.map